### ISSUE TITLE
Diamond harness uncraftable

### ISSUE THREAD

**Issue by minakitty** [Frost2779/Elytra_Crafting#2]
I have the config set to allow crafting of elytra pre-End, and noticed it was essentially uncraftable.  The Diamond Harness (ecm:diamond_harness) has no recipe associated with it and while the leather harness is craftable, it's not usable.  Using it as a template, I made a potential recipe for it in CraftTweaker, hopefully with similar balance using four diamond reinforced sticks and four diamond reinforced hardened leather

```# (c) 2019 Sera de Noir under MIT License
# Elytra Crafting Mod tweak to fix harness crafting

# Requirements: Elytra Crafting Mod

val DH = <ecm:diamond_harness>;
val DRS = <ecm:diamond_reinforced_stick>;
val DRHLS = <ecm:diamond_reinforced_hard_leather_square>;

recipes.addShaped("ACX_Elytra_Diamond_Harness", DH,
[[DRS,DRHLS,DRS],
 [DRHLS,null,DRHLS],
 [DRS,DRHLS,DRS]]);```

**Comment by Frost2779** [comment]
I found the issue, there was a typo in the recipe file that was casing it to not register correctly. It has been fixed an I will be pushing an update here within the hour. Also, the Leather harness was part of a left over experiment earlier on in development, it has now been removed.

**Comment by minakitty** [comment]
Cool!
